sudo: false
dist: bionic

language: php

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.4
      env: WP_VERSION=latest

before_script:
  - bash bin/before-script.sh

script:
  - |
    cd "${THEMES_DIR}travis-test"
    phpunit
    WP_TESTS_SKIP_INSTALL=0 WP_MULTISITE=1 phpunit
  - |
    cd "${PLUGINS_DIR}travis-test"
    phpunit
    WP_TESTS_SKIP_INSTALL=0 WP_MULTISITE=1 phpunit
